### ISSUE TITLE
Youtube downloads are broken

### ISSUE THREAD

**Issue by amckee** [amckee/PodTube#1]
I'm pretty sure that was me. Gonna fix it, but kinda want to just focus on replacing the API method with a scraping method 'cause Youtube API's are a PITA.

We will see, but I know it's broken at the moment.

**Comment by amckee** [comment]
Works fine locally, does not work on the production server. Tried dropping firewall to no affect. The error:
`2021-06-28 14:01:03,199 500 GET /video/uLNLshRtazw (<redacted>) 2875.63ms
2021-06-28 14:03:45,545 Video: pEnzg8Fca8w
2021-06-28 14:03:45,556 Full URL: http://www.youtube.com/watch?v=pEnzg8Fca8w
2021-06-28 14:03:45,556 matched regex search: (?:v=|\/)([0-9A-Za-z_-]{11}).*
2021-06-28 14:03:47,371 Uncaught exception GET /video/pEnzg8Fca8w (<redacted>)
HTTPServerRequest(protocol='http', host='<redacted>', method='GET', uri='/video/pEnzg8Fca8w', version='HTTP/1.1', remote_ip='<redacted>')
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/PodTube/youtube.py", line 465, in get
    self.redirect(get_youtube_url(video))
  File "/var/www/PodTube/youtube.py", line 118, in get_youtube_url
    vid = yt.streams.get_highest_resolution().url
  File "/usr/local/lib/python3.6/site-packages/pytube/__main__.py", line 310, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.6/site-packages/pytube/__main__.py", line 213, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "/usr/local/lib/python3.6/site-packages/pytube/__main__.py", line 187, in player_config_args
    self._player_config_args = self.vid_info
  File "/usr/local/lib/python3.6/site-packages/pytube/__main__.py", line 280, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "/usr/local/lib/python3.6/site-packages/pytube/__main__.py", line 108, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "/usr/local/lib/python3.6/site-packages/pytube/request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/pytube/request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
2021-06-28 14:03:47,380 500 GET /video/pEnzg8Fca8w (<redacted>) 1837.38ms`
