### ISSUE TITLE
How to authenticate an ubuntu server in the google api?

### ISSUE THREAD

**Issue by yareblo** [amckee/PodTube#26]
Hi,

sorry if this is a complete noob-question, but maybe someone can help. I have successfully installed the docker image, and I can subscripe to an user with my podcast app, and I see the podcasts listed. However, when I start downoading a podcast, I get the following error:

Please open https://www.google.com/device and input code XXX-XXX-XXX
Press enter when you have completed this step.2024-11-30 15:10:19,848 [ERROR] Uncaught exception GET /youtube/video/n0trelevant (95.117.137.83)
HTTPServerRequest(protocol='http', host='xx.xx.xx.xx:15000', method='GET', uri='/youtube/video/n0trelevant', version='HTTP/1.1', remote_ip='xx.xx.xx.xx')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/youtube.py", line 722, in get
    yt_url = get_youtube_url(video)
  File "/opt/youtube.py", line 275, in get_youtube_url
    vid = yt.streams.get_highest_resolution().url
  File "/usr/local/lib/python3.10/site-packages/pytubefix/__main__.py", line 636, in streams
    self.check_availability()
  File "/usr/local/lib/python3.10/site-packages/pytubefix/__main__.py", line 316, in check_availability
    status, messages = extract.playability_status(self.vid_info)
  File "/usr/local/lib/python3.10/site-packages/pytubefix/__main__.py", line 425, in vid_info
    innertube_response = innertube.player(self.video_id)
  File "/usr/local/lib/python3.10/site-packages/pytubefix/innertube.py", line 807, in player
    return self._call_api(endpoint, query, self.base_data)
  File "/usr/local/lib/python3.10/site-packages/pytubefix/innertube.py", line 701, in _call_api
    self.fetch_bearer_token()
  File "/usr/local/lib/python3.10/site-packages/pytubefix/innertube.py", line 623, in fetch_bearer_token
    self.oauth_verifier(verification_url, user_code)
  File "/usr/local/lib/python3.10/site-packages/pytubefix/innertube.py", line 457, in _default_oauth_verifier
    input('Press enter when you have completed this step.')
EOFError: EOF when reading a line

How can I authenticate the device (=the server) without a browser on it? I have opened google.com/device on another device and entered the code, but this does not seem to help.

**Comment by yareblo** [comment]
There is a workaround for the issue:

in youtube.py, change line 259 to:

      ` yt = YouTube(yturl, use_oauth=False, allow_oauth_cache=True, client='ANDROID')`

which is basically switching off the oauth in function get_youtube_url.

This helps in my case, where I do not need to use my youtube-account. But sill, it would be great if someone has a solution for the issue.

**Comment by amckee** [comment]
This is an ongoing problem as Youtube keeps changing things on their side to prevent tools like these from working. These changes occasionally break things. Podtube uses [pytubefix](https://github.com/JuanBindez/pytubefix) to handle the Youtube things, so really the issue should be sorted out over there.

In short, though, it's looking for a PO Token. How to get one without it linked to an actual account is detailed here, along with other options:
https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide

I'm going to close this issue because there isn't much that Podtube itself can do about this, though I am exploring an experimental branch that uses [yt-dlp](https://github.com/yt-dlp/yt-dlp) instead of pytubefix to see if that increases download stability.
