### ISSUE TITLE
YouTube channel ID's being used instead of names 

### ISSUE THREAD

**Issue by amckee** [amckee/PodTube#7]
It seems youtube changed their API data returns, the 'snippet' object no longer contains the 'channelTitle' string:

```
HTTPServerRequest(protocol='http', host='[hostname]:15000', method='GET', uri='/youtube/channel/UCpQu57KgT7gOoLCAu3FFQsA', version='HTTP/1.1', remote_ip='[ip_address]')
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "/var/www/PodTube/youtube.py", line 232, in get
    snippet['channelTitle']
KeyError: 'channelTitle'
```

A temporary work around has been implemented to use the channel ID instead:
https://github.com/amckee/PodTube/commit/ab98cea21a9a4d2248a633183f9a9239877a431c

**Comment by amckee** [comment]
Looks like Youtube's API did not provide this information for a bit, but has since been fixed.
