### ISSUE TITLE
Rumble Broken

### ISSUE THREAD

**Issue by amckee** [amckee/PodTube#8]
Just noticed that rumble channels are no longer pulling:

```
2022-12-09 17:36:21,635 Got channel: <CHANNELNAME>
2022-12-09 17:36:21,635 Handling Rumble URL: https://rumble.com/c/<CHANNELNAME>
2022-12-09 17:36:21,635 Channel: <CHANNELNAME>
2022-12-09 17:36:21,635 Rumble URL: https://rumble.com/c/<CHANNELNAME>
2022-12-09 17:36:21,638 Starting new HTTPS connection (1): rumble.com:443
2022-12-09 17:36:21,732 https://rumble.com:443 "GET /c/<CHANNELNAME> HTTP/1.1" 200 None
2022-12-09 17:36:21,817 Uncaught exception GET /rumble/channel/<CHANNELNAME> (<REMOTEIP>)
HTTPServerRequest(protocol='http', host='<SERVERNAME>:15000', method='GET', uri='/rumble/channel/<CHANNELNAME>', version='HTTP/1.1', remote_ip='<REMOTEIP>')
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/PodTube/rumble.py", line 23, in get
    feed = self.generate_rss( channel )
  File "/var/www/PodTube/rumble.py", line 43, in generate_rss
    feed.title( bs.find("h1", "listing-header--title").text )
AttributeError: 'NoneType' object has no attribute 'text'
2022-12-09 17:36:21,817 500 GET /rumble/channel/<CHANNELNAME> (<REMOTEIP) 183.03ms

```

**Comment by amckee** [comment]
https://github.com/amckee/PodTube/commit/02f3e479be71a6def70fb8623802fefb918790da
